# config/packages/easy_admin.yaml
easy_admin:
  entities:
    # change the following to the namespaces of your own entities
    - App\Entity\Category
    - App\Entity\User
    - App\Entity\Post
    - App\Entity\Comment